spring:
  application:
     name: quickcart-backend
  config:
    import: classpath:configuration/resilience4j.yml
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/quickcart_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none   # disable auto-magic schema changes
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: ${FLYWAY_BASELINE:false}  # ONLY for the first run on an existing DB
  cache:
    type: caffeine

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI}

keycloak:
  url: ${KEYCLOAK_URL:http://keycloak:8080}
  realm: ${KEYCLOAK_REALM:quickcart}
  admin-client-id: ${KEYCLOAK_CLIENT_ID:quickcart-backend}
  admin-client-secret: ${KEYCLOAK_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    org.springframework.security: INFO

# APPLICATION PROPERTIES
app:
  admin:
    username: ${APP_ADMIN_USERNAME}
    password: ${APP_ADMIN_PASSWORD}