spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/quickcart_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update   # set update for quick dev, use validate + Flyway in prod
    properties:
      hibernate:
        format_sql: false
  cache:
    type: caffeine

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8080/realms/myrealm/protocol/openid-connect/certs}

keycloak:
  url: http://keycloak:8080
  realm: quickcart
  admin-client-id: quickcart-backend
  admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    org.springframework.security: INFO
