spring:
  application:
     name: quickcart-backend
  config:
    import:
    - classpath:configuration/resilience4j.yml
    - optional:file:.env[.properties]

  # Web/Static resource configuration
  mvc:
    # map all static resource requests to /docs/**
    static-path-pattern: "/docs/**"
  # where Spring looks for static files (keep your existing locations)
  web:
    resources:
      static-locations:
        - "classpath:/static/"
        - "classpath:/public/"

  # Datasource configuration
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none   # disable auto-magic schema changes
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  # Flyway migration configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: ${FLYWAY_BASELINE:false}  # ONLY for the first run on an existing DB

  # Cache Configuration
  cache:
    type: caffeine

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI}

keycloak:
  url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  admin-client-id: ${KEYCLOAK_CLIENT_ID}
  admin-client-secret: ${KEYCLOAK_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.donkie.quickcart: DEBUG

# APPLICATION PROPERTIES
app:
  admin:
    username: ${APP_ADMIN_USERNAME}
    password: ${APP_ADMIN_PASSWORD}