server:
  port: 8081


# ================ Spring & Integrated Libraries Configuration ================
spring:
  application:
     name: quickcart-backend
  config:
    import:
    - classpath:configuration/resilience4j.yml
    - classpath:configuration/internal.yml
    - optional:file:.env[.properties]

  # ----------------- Web/Static resource configuration -----------------
  mvc:
    static-path-pattern: "/docs/**" # map all static resource requests to /docs/**
  web:
    resources:
      static-locations:
        - "classpath:/static/"
        - "classpath:/public/"

  # ----------------- Datasource configuration -----------------
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none   # disable auto-magic schema changes
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  # ----------------- Flyway migration configuration -----------------
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: ${FLYWAY_BASELINE:false}  # ONLY for the first run on an existing DB

  # ----------------- Cache Configuration -----------------
  cache:
    type: caffeine

  # ----------------- Security Configuration -----------------
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI}


# ================ Monitoring & Health ================
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never


# ================ Logging & Debugging ================
logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.donkie.quickcart: DEBUG